version: 1.0.1
slug: dnsmasq
name: Dnsmasq with DHCP
description: DHCP server based on Dnsmasq
url: https://github.com/knollpoi/hass_addons/tree/master/dnsmasq
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
# image: knollpoi/{arch}-addon-dnsmasq-dhcp
init: false
host_network: true
privileged:
  - NET_ADMIN
options:
#  dns_default_resolvers: []
#  dns_forwards: []
#  dns_hosts: []
#  dns_services: []
  raw_config: []
  dhcp_ranges: []
  dhcp_options: []
  dhcp_hosts: []
  vendor_options: []
  vendor_class: []
  domains: []
schema:
  raw_config:
    - "str?"
  domains:
    - domain: "str?"
      network: "str?"
      start: "str?"
      end: "str?"
  dhcp_ranges:
    - set: "str?"
      tag: "str?"
      start: str
      end: str
      mask: str
      leasetime: str
  dhcp_options:
    - tag: "str?"
      option: str
      value: str
  dhcp_hosts:
    - hostname: "str?"
      mac_address: "str?"
      ipv4address: "str?"
      ignore: "str?"
      set: "str?"
  vendor_options:
    - value: str
      tag: "str?"
  vendor_class:
    - set: "str?"
      class_string: "str?"
#  dns_default_resolvers:
#    - str
#  dns_forwards:
#    - domain: str
#      server: str
#  dns_hosts:
#    - host: str
#      ip: str
#  dns_services:
#    - host: str
#      port: str
#      priority: int
#      srv: str
#      weight: int

startup: system
