version: 1.4.4
slug: dnsmasq
name: Dnsmasq
description: A simple DNS server
url: https://github.com/home-assistant/hassio-addons/tree/master/dnsmasq
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: homeassistant/{arch}-addon-dnsmasq
init: false
host_network: true
options:
  rawconfig: |+
no-resolv
no-hosts
keep-in-foreground
log-queries
log-facility=-
no-poll
user=root

schema:
  rawconfig::
    - str

startup: system
